### ISSUE TITLE
Test ok?

### ISSUE THREAD

**Issue by TobiasSMI** [nobody1337/CL_Tasks#1]
https://github.com/nobody1337/CL_Tasks/blob/064acd8c518aa97a2bf58dcafc1dd44364be47f0/src/main/java/CodewarsTasks/SumArrays/SumArray.java#L39

Waren die Tests in Ordnung? In der Aufgabe steht du sollst 0 zurückgeben, du gibst jedoch die Fließkommazahl 0.0 zurück.
Falls die Tests jedoch alle grün waren, kannst du das ignorieren.

**Comment by nobody1337** [comment]
Die Tests waren alle in Ordnung
