### ISSUE TITLE
IgnoreCase

### ISSUE THREAD

**Issue by TobiasSMI** [nobody1337/CL_Tasks#2]
https://github.com/nobody1337/CL_Tasks/blob/064acd8c518aa97a2bf58dcafc1dd44364be47f0/src/main/java/CodewarsTasks/Banjo/Banjo.java#L14

Versuch hier an der Stelle bitte mal die ignoreCase Funktion zu nutzen. Und bitte finde heraus, ob der ursprüngliche String (im speziellen das Format der Zeichen) erhalten bleibt. 

Falls nein:
<details>  <summary>Klick</summary>  
  Was müsste getan werden, damit der String dauerhaft verändert ist?
</details>

**Comment by nobody1337** [comment]
Habe die ignoreCase Funktion nachträglich verwendet.
